#!/usr/bin/env perl
use Term::ReadLine;
use autodie;

my $password = do {
    my $rl = Term::ReadLine->new("add-password");
    $rl->readline("password> ") . "\n";
};

my @lines = `gpg --decrypt $ENV{HOME}/.passes`;
die if !@lines;

open my $child, "| gpg -r $ENV{EMAIL} --encrypt -o $ENV{HOME}/.passes"
    or die "Unable to open gpg for encrypting.";
print {$child} $_ for @lines, $password;

