#!/usr/bin/env perl
use strict;
use warnings;
use Lingua::JP::Kanjidic;
use Encode 'decode_utf8';
my $dic = Lingua::JP::Kanjidic->new("$ENV{HOME}/.kanjidic");

binmode(\*STDOUT, ':utf8');

my %is_sought = map { $_ => 1 }
                grep { /\p{Han}/ }
                split //,
                decode_utf8("@ARGV");

while (my $kanji = $dic->next) {
    next if !$is_sought{$kanji->kanji};

    print $kanji->kanji;
    print ' (' . $kanji->heiseg . ')' if $kanji->heiseg;
    print ': ';
    print join(', ', @{ $kanji->meaning || ["???"] });
    print "\n";
}


