#!/usr/bin/env perl
use strict;
use warnings;
use Lingua::JP::Kanjidic;
my $dic = Lingua::JP::Kanjidic->new("$ENV{HOME}/.kanjidic");

binmode(\*STDOUT, ':utf8');
binmode(\*STDERR, ':utf8');
$\ = "\n";

my $code = eval "sub {
    use utf8;
    $ARGV[0];
}";

while (my $kanji = $dic->next) {
    local $_ = $kanji;
    $code->($_);
}

