#!/bin/sh
DIRNAME="$1_mysql"
DBNAME=`echo "rt_$1" | perl -ple 's/-/_/g; s/\.//g'`

./configure.ac
./configure --prefix=/opt/rt/$DIRNAME --enable-graphviz --enable-gd --enable-gpg --with-my-user-group --with-db-database=$DBNAME --with-db-type=mysql --with-db-dba=root

make install

rm -f /opt/rt3
ln -vis /opt/rt/$DIRNAME /opt/rt3

rm -rf /opt/rt3/var/mason_data
