#!/bin/sh
BRANCH=`git branch | grep '^*' | head -n1 | cut -c 3- | tr / -`
RTNAME=${1:-$BRANCH}
DBNAME=`echo "rt_$RTNAME" | perl -ple 's/-/_/g; s/\.//g'`
DIRNAME="${RTNAME}_sqlite"


./configure.ac
./configure --prefix=/opt/rt/$DIRNAME --enable-graphviz --enable-gd --enable-gpg --with-my-user-group --with-db-database=$DBNAME --with-db-type=SQLite

make install

rm -f /opt/rt3
ln -vis /opt/rt/$DIRNAME /opt/rt3

rm -rf /opt/rt3/var/mason_data
