#!/usr/bin/env perl
use strict;
use warnings;

die "No input specified\n" if @ARGV == 0;

print "Transliteration: ";
system("transliterate", @ARGV);
print "\n";

print "Kanji:\n";
system("define-kanji", @ARGV);

