#!/usr/bin/env perl
use strict;
use warnings;

print "Translation: ";
system("ja2en", @ARGV);
print "\n";

print "Transliteration: ";
system("transliterate", @ARGV);
print "\n";

print "Kanji:\n";
system("define-kanji", @ARGV);

