#!/bin/sh
# find unsuspended sentences which contain kanji for which the reading field is empty
# so I can add that reading field

echo "select kanji.value, sentence.value
    from fields as sentence
        join fields as kanji on (sentence.value like ('%'||kanji.value||'%'))
        join fields as reading on (kanji.factId = reading.factId)
        join cards on (cards.factId = sentence.factId)
    where
        reading.fieldModelId=1870991842743010604
        and sentence.fieldModelId=4775683831775348908
        and kanji.fieldModelId=7694462791390410032
        and reading.value=''
        and cards.type>0
        order by kanji.value;" | sqlite3 ~/Documents/Anki/Japanese.anki | perl5i -nle 'our (%seen, $i); my ($kanji, $sentence) = /(.)\|(.+)/; print "\n\n".++$i.". $kanji:" if $seen{$kanji}++==0; print "  $sentence"'

# example output
# 35. 球:
#   皆の者よ ここは地球という星だ
#   ガラスの球をみつけた
#   おまえどこからきた　地球か？
#
# 38. 直:
#  直ぐ行きます。
#  正直ねむい
#
# 48. 縄:
#  沖縄はずっと南の方だ
