#!/usr/bin/env perl
use 5.12.0;
use warnings;
use Net::LastFM::Submission;
use YAML;
use Getopt::Whatever;

my $submit = Net::LastFM::Submission->new(
    %{ YAML::LoadFile(glob "~/.last.fm") }
);

$submit->handshake;

die "usage: $0 --artist='whatever' --title='whatever'\n"
    unless $ARGV{artist} && $ARGV{title};

$submit->submit(time => time, %ARGV);

