#!/usr/bin/env perl
use 5.14.0;
use warnings;
use Weather::Underground::Forecast;

chomp(my $latlon = `whereami`);
my $forecast = Weather::Underground::Forecast->new(
    location => $latlon,
);
say $forecast->precipitation->[0] . '%';
