#!/usr/bin/env perl
use strict;
use warnings;
use Lingua::JA::Romanize::Japanese;
use Encode 'decode_utf8';

my $text = decode_utf8 "@ARGV";
binmode(\*STDOUT, ':utf8');
print Lingua::JA::Romanize::Japanese->new->chars($text) . "\n";

