#!/usr/bin/env perl
use strict;
use warnings;
use Weather::Google;

my $weather = Weather::Google->new(shift || '02144');

my $days = $weather->forecast_conditions;
for my $day (@$days) {
    print "[$day->{day_of_week}] $day->{low}-$day->{high}: $day->{condition}\n";
}

